version: '3.8'

services:
  postgres:
    container_name: reactive
    image: postgres:latest
    ports:
      - '5433:5432'
    volumes:
      - local-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=localhost

volumes:
  local-postgres:
