spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/reactive
    username: postgres
    password: root
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/reactive
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
